stages:
  - build

frontend-build:
  stage: build
  only:
    - staging
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_TLS_CERTDIR: ""
  script:
    # Se connecter à Docker Hub
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    # Construire l'image Docker
    - docker build --no-cache -t $DOCKERHUB_USERNAME/my-app:$CI_COMMIT_REF_SLUG -f docker/development/Dockerfile .
    # Pousser l'image Docker sur Docker Hub
    - docker push $DOCKERHUB_USERNAME/my-app:$CI_COMMIT_REF_SLUG
