stages:
  - build

variables:
  # Nom de l'image Docker avec son tag basé sur le hash du commit
  DOCKER_IMAGE: "registry.gitlab.polytech.umontpellier.fr/vincent.dubuc/cd-ci:staging-${CI_COMMIT_SHORT_SHA}"

build-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  only:
    - staging
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t $DOCKER_IMAGE -f cd-ci/docker/development/Dockerfile .
    - docker push $DOCKER_IMAGE
