stages:
  - build
  - deploy

frontend-build:
  stage: build
  only:
    - staging
  variables:
    DOCKER_DRIVER: overlay
  script:
    # Construire et tagger l'image Docker
    - docker build --no-cache -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG -f cd-ci/docker/development/Dockerfile .
    # Se connecter au registre GitLab
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # Pousser l'image Docker dans le registre
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
